### ISSUE TITLE
Dependencies (kdyby/curl) are broken

### ISSUE THREAD

**Issue by Aurielle** [Aurielle/Yui-chan#7]
Cause I deleted my forked repo and didn't think of consequences…

**Comment by this-amazing-amy** [comment]
Is there any way to fix this?

**Comment by Aurielle** [comment]
@murmox I tried to recreate and repush to the repo from my local files, please test.

**Comment by this-amazing-amy** [comment]
Cool, it works now. Arigatou, Yui-chan. ^^
I had to run composer update instead of composer install, maybe you can update the readme to prevent confusion for future users.
Nice tool, btw.

**Comment by Aurielle** [comment]
Thanks, but the code is a mess, really :D I should rewrite it.
